config/routes.rb
Rails.application.routes.draw do
  resources :emps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emp.rb
class Emp < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid email format" }
    validates :contact, presence: true, length: { minimum: 10, maximum: 15 }
    validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  before_action :set_emp, only: %i[ show edit update destroy ]

  # GET /emps or /emps.json
  def index
    @emps = Emp.all
  end

  # GET /emps/1 or /emps/1.json
  def show
  end

  # GET /emps/new
  def new
    @emp = Emp.new
  end

  # GET /emps/1/edit
  def edit
  end

  # POST /emps or /emps.json
  def create
    @emp = Emp.new(emp_params)

    respond_to do |format|
      if @emp.save
        format.html { redirect_to emp_url(@emp), notice: "Emp was successfully created." }
        format.json { render :show, status: :created, location: @emp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emps/1 or /emps/1.json
  def update
    respond_to do |format|
      if @emp.update(emp_params)
        format.html { redirect_to emp_url(@emp), notice: "Emp was successfully updated." }
        format.json { render :show, status: :ok, location: @emp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1 or /emps/1.json
  def destroy
    @emp.destroy

    respond_to do |format|
      format.html { redirect_to emps_url, notice: "Emp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emp
      @emp = Emp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def emp_params
      params.require(:emp).permit(:name, :email, :contact, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/views/emps/_form.html.erb
<%= form_with(model: emp) do |form| %>
  <% if emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
        <% emp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing Emp</h1>

<%= render 'form', emp: @emp %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emps.each do |emp| %>
      <tr>
        <td><%= emp.name %></td>
        <td><%= emp.email %></td>
        <td><%= emp.contact %></td>
        <td><%= emp.address %></td>
        <td><%= link_to 'Show', emp %></td>
        <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
        <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emp', new_emp_path %>

app/views/emps/new.html.erb
<h1>New Emp</h1>

<%= render 'form', emp: @emp %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @emp.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @emp.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @emp.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @emp.address %>
</p>

<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empoyee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>